/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Create_Vector.java
 *
 * Created on Jul 28, 2009, 11:29:02 PM
 */

package vectors;

/**
 *
 * @author Dinesh
 */
public class Create_Vector extends javax.swing.JFrame {

    private String name;
    private double x_comp;
    private double y_comp;
    private double z_comp;
    private boolean localize;

    private Vector v;
   // private boolean is_ok_pressed;
    
    /** Creates new form Create_Vector */
    public Create_Vector() {
        initComponents();
        getDefault();
        setFields();
    }

    private void getDefault(){
        name = "";
        x_comp = 0;
        y_comp = 0;
        z_comp = 0;
        localize = true;
    }

    private void setFields(){
        //this.name_field.setText(name);
        this.x_comp_field.setText(Double.toString(x_comp));
        this.y_comp_field.setText(Double.toString(y_comp));
        this.z_comp_field.setText(Double.toString(z_comp));
        this.is_localizable_field.setSelected(localize);
    }

    public void setFields(int in){
        if(in == -1){
            v = Vector_Storage.getVector("D");

        }
        else{
            v = Vector_Storage.getVector(select_name.getItemAt(in).toString());
        }

        x_comp = v.getX();
        y_comp = v.getY();
        z_comp = v.getZ();
        localize = v.getLocalizable();
        this.name = v.getName();
        select_name.setSelectedIndex(in);
        this.setFields();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        x_comp_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        x_comp_field = new javax.swing.JFormattedTextField();
        y_comp_field = new javax.swing.JFormattedTextField();
        z_comp_field = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        is_localizable_field = new javax.swing.JCheckBox();
        ok_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        select_name = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(vectors.VectorsApp.class).getContext().getResourceMap(Create_Vector.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        x_comp_label.setText(resourceMap.getString("x_comp_label.text")); // NOI18N
        x_comp_label.setName("x_comp_label"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        x_comp_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        x_comp_field.setText(resourceMap.getString("x_comp_field.text")); // NOI18N
        x_comp_field.setName("x_comp_field"); // NOI18N

        y_comp_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        y_comp_field.setText(resourceMap.getString("y_comp_field.text")); // NOI18N
        y_comp_field.setName("y_comp_field"); // NOI18N

        z_comp_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        z_comp_field.setText(resourceMap.getString("z_comp_field.text")); // NOI18N
        z_comp_field.setName("z_comp_field"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        is_localizable_field.setText(resourceMap.getString("is_localizable_field.text")); // NOI18N
        is_localizable_field.setName("is_localizable_field"); // NOI18N

        ok_button.setText(resourceMap.getString("ok_button.text")); // NOI18N
        ok_button.setName("ok_button"); // NOI18N
        ok_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_buttonMouseClicked(evt);
            }
        });

        cancel_button.setText(resourceMap.getString("cancel_button.text")); // NOI18N
        cancel_button.setName("cancel_button"); // NOI18N
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseClicked(evt);
            }
        });

        reset_button.setText(resourceMap.getString("reset_button.text")); // NOI18N
        reset_button.setName("reset_button"); // NOI18N
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_buttonMouseClicked(evt);
            }
        });

        select_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        select_name.setName("select_name"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cancel_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(reset_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(x_comp_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_name, 0, 144, Short.MAX_VALUE)
                            .addComponent(is_localizable_field, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(z_comp_field, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(y_comp_field, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(x_comp_field, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(x_comp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_comp_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_comp_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(z_comp_field, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(is_localizable_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_button)
                    .addComponent(cancel_button)
                    .addComponent(reset_button))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseClicked
        this.getDefault();
        this.setFields();
    }//GEN-LAST:event_reset_buttonMouseClicked

    public void setName(String name){
        this.name = name;
    }
    private void ok_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_buttonMouseClicked
        this.setVisible(false);

        this.name   = select_name.getSelectedItem().toString();
        this.x_comp = Double.parseDouble(x_comp_field.getText());
        this.y_comp = Double.parseDouble(y_comp_field.getText());
        this.z_comp = Double.parseDouble(z_comp_field.getText());
        this.localize = is_localizable_field.isSelected();

        v = new Vector(this.x_comp, this.y_comp, this.z_comp, this.name, localize);

        Vector_Storage.setVector(v, name);
//        this.is_ok_pressed = true;
    }//GEN-LAST:event_ok_buttonMouseClicked

    private void cancel_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseClicked
        this.setVisible(false);
  //      this.is_ok_pressed = false;
    }//GEN-LAST:event_cancel_buttonMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

 /*   public Vector getVector(){
        if(this.is_ok_pressed){
            return v;
        }
        else{
            return null;
        }
    }*/
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Vector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JCheckBox is_localizable_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok_button;
    private javax.swing.JButton reset_button;
    private javax.swing.JComboBox select_name;
    private javax.swing.JFormattedTextField x_comp_field;
    private javax.swing.JLabel x_comp_label;
    private javax.swing.JFormattedTextField y_comp_field;
    private javax.swing.JFormattedTextField z_comp_field;
    // End of variables declaration//GEN-END:variables

}
