/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Keyboard.java
 *
 * Created on Jul 29, 2009, 2:20:30 PM
 */

package vectors;

/**
 *
 * @author Dinesh
 */
public class Keyboard extends javax.swing.JFrame {

    String expression = " ";
    /** Creates new form Keyboard */
    public Keyboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        vec_a = new javax.swing.JButton();
        vec_b = new javax.swing.JButton();
        vec_c = new javax.swing.JButton();
        dot_pr = new javax.swing.JButton();
        cr_pr = new javax.swing.JButton();
        add = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        sc_tr_product = new javax.swing.JButton();
        vc_tr_product = new javax.swing.JButton();
        close_brace = new javax.swing.JButton();
        open_brace = new javax.swing.JButton();
        comma = new javax.swing.JButton();
        ok_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(vectors.VectorsApp.class).getContext().getResourceMap(Keyboard.class);
        input.setText(resourceMap.getString("input.text")); // NOI18N
        input.setName("input"); // NOI18N

        vec_a.setText(resourceMap.getString("vec_a.text")); // NOI18N
        vec_a.setName("vec_a"); // NOI18N
        vec_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vec_aMouseClicked(evt);
            }
        });

        vec_b.setText(resourceMap.getString("vec_b.text")); // NOI18N
        vec_b.setName("vec_b"); // NOI18N
        vec_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vec_bMouseClicked(evt);
            }
        });

        vec_c.setText(resourceMap.getString("vec_c.text")); // NOI18N
        vec_c.setName("vec_c"); // NOI18N
        vec_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vec_cMouseClicked(evt);
            }
        });

        dot_pr.setText(resourceMap.getString("dot_pr.text")); // NOI18N
        dot_pr.setName("dot_pr"); // NOI18N
        dot_pr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dot_prMouseClicked(evt);
            }
        });

        cr_pr.setText(resourceMap.getString("cr_pr.text")); // NOI18N
        cr_pr.setName("cr_pr"); // NOI18N
        cr_pr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cr_prMouseClicked(evt);
            }
        });

        add.setText(resourceMap.getString("add.text")); // NOI18N
        add.setName("add"); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        subtract.setText(resourceMap.getString("subtract.text")); // NOI18N
        subtract.setName("subtract"); // NOI18N
        subtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtractMouseClicked(evt);
            }
        });

        multiply.setText(resourceMap.getString("multiply.text")); // NOI18N
        multiply.setName("multiply"); // NOI18N
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyMouseClicked(evt);
            }
        });

        sc_tr_product.setText(resourceMap.getString("sc_tr_product.text")); // NOI18N
        sc_tr_product.setName("sc_tr_product"); // NOI18N
        sc_tr_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sc_tr_productMouseClicked(evt);
            }
        });

        vc_tr_product.setText(resourceMap.getString("vc_tr_product.text")); // NOI18N
        vc_tr_product.setName("vc_tr_product"); // NOI18N
        vc_tr_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vc_tr_productMouseClicked(evt);
            }
        });

        close_brace.setText(resourceMap.getString("close_brace.text")); // NOI18N
        close_brace.setName("close_brace"); // NOI18N
        close_brace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_braceMouseClicked(evt);
            }
        });

        open_brace.setText(resourceMap.getString("open_brace.text")); // NOI18N
        open_brace.setName("open_brace"); // NOI18N
        open_brace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_braceMouseClicked(evt);
            }
        });

        comma.setText(resourceMap.getString("comma.text")); // NOI18N
        comma.setName("comma"); // NOI18N
        comma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commaMouseClicked(evt);
            }
        });

        ok_button.setText(resourceMap.getString("ok_button.text")); // NOI18N
        ok_button.setName("ok_button"); // NOI18N
        ok_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_buttonMouseClicked(evt);
            }
        });

        reset_button.setText(resourceMap.getString("reset_button.text")); // NOI18N
        reset_button.setName("reset_button"); // NOI18N
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(close_brace, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(subtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(sc_tr_product)
                                        .addComponent(vc_tr_product))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(dot_pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cr_pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(open_brace, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(60, 60, 60)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(vec_a, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(vec_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vec_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_brace)
                    .addComponent(open_brace)
                    .addComponent(comma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(add)
                    .addComponent(sc_tr_product)
                    .addComponent(dot_pr)
                    .addComponent(vec_a))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(subtract)
                    .addComponent(vc_tr_product)
                    .addComponent(cr_pr)
                    .addComponent(vec_b))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(multiply)
                    .addComponent(vec_c))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_button)
                    .addComponent(reset_button))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseClicked
        input.setText("");
    }//GEN-LAST:event_reset_buttonMouseClicked

    private void commaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commaMouseClicked
        input.setText(",");
    }//GEN-LAST:event_commaMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        input.setText("Add");
    }//GEN-LAST:event_addMouseClicked

    private void subtractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractMouseClicked
       input.setText("Subtract");
    }//GEN-LAST:event_subtractMouseClicked

    private void multiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseClicked
        input.setText("Multiply");
    }//GEN-LAST:event_multiplyMouseClicked

    private void sc_tr_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sc_tr_productMouseClicked
        input.setText("SC_TRIPLE_PRODUCT");
    }//GEN-LAST:event_sc_tr_productMouseClicked

    private void vc_tr_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vc_tr_productMouseClicked
        input.setText("VC_TRIPLE_PRODUCT");
    }//GEN-LAST:event_vc_tr_productMouseClicked

    private void dot_prMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dot_prMouseClicked
        input.setText("DOT_PRODUCT");
    }//GEN-LAST:event_dot_prMouseClicked

    private void cr_prMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cr_prMouseClicked
        input.setText("CROSS_PRODUCT");
    }//GEN-LAST:event_cr_prMouseClicked

    private void close_braceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_braceMouseClicked
        input.setText(")");
    }//GEN-LAST:event_close_braceMouseClicked

    private void open_braceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_braceMouseClicked
        input.setText("(");
    }//GEN-LAST:event_open_braceMouseClicked

    private void vec_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vec_aMouseClicked
        input.setText("A");
    }//GEN-LAST:event_vec_aMouseClicked

    private void vec_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vec_bMouseClicked
        input.setText("B");
    }//GEN-LAST:event_vec_bMouseClicked

    private void vec_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vec_cMouseClicked
        input.setText("C");
    }//GEN-LAST:event_vec_cMouseClicked

    private void ok_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_buttonMouseClicked
        this.expression = input.getText();
        this.setVisible(false);
    }//GEN-LAST:event_ok_buttonMouseClicked

    public String getExpression(){
        return this.expression;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keyboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton close_brace;
    private javax.swing.JButton comma;
    private javax.swing.JButton cr_pr;
    private javax.swing.JButton dot_pr;
    private javax.swing.JTextField input;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiply;
    private javax.swing.JButton ok_button;
    private javax.swing.JButton open_brace;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton sc_tr_product;
    private javax.swing.JButton subtract;
    private javax.swing.JButton vc_tr_product;
    private javax.swing.JButton vec_a;
    private javax.swing.JButton vec_b;
    private javax.swing.JButton vec_c;
    // End of variables declaration//GEN-END:variables

}
