/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Select_a_Vector.java
 *
 * Created on Jul 29, 2009, 11:27:42 AM
 */

package vectors;

/**
 *
 * @author Dinesh
 */
public class Select_a_Vector extends javax.swing.JFrame {

    /*
     * OPCODE HAS FOLLOWING VALUES...
     * 0: Create a Vector..
     * 1: Modify a Vector..
     * 2: Remove a Vector..
     * 3: Display a Vector..
     */
    public int opCode;
    Create_Vector cv;
    
    /** Creates new form Select_a_Vector */
    public Select_a_Vector() {
        initComponents();
        otherInitilization();
    }

    public void otherInitilization(){
        //this.select_box.set
        cv = new Create_Vector();
        display_panel.setVisible(false);
    }

    public void setOpCode(int opcode){
        this.opCode = opcode;
    }

    public void startMe(){
        this.setVisible(true);
        display_panel.setVisible(false);
        selection_panel.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selection_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        select_box = new javax.swing.JComboBox();
        select_ok_button = new javax.swing.JButton();
        display_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        display_field = new javax.swing.JLabel();
        display_ok_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        selection_panel.setBorder(new javax.swing.border.MatteBorder(null));
        selection_panel.setName("selection_panel"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(vectors.VectorsApp.class).getContext().getResourceMap(Select_a_Vector.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setName("jLabel1"); // NOI18N

        select_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        select_box.setName("select_box"); // NOI18N

        select_ok_button.setText(resourceMap.getString("select_ok_button.text")); // NOI18N
        select_ok_button.setName("select_ok_button"); // NOI18N
        select_ok_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                select_ok_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout selection_panelLayout = new javax.swing.GroupLayout(selection_panel);
        selection_panel.setLayout(selection_panelLayout);
        selection_panelLayout.setHorizontalGroup(
            selection_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selection_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(selection_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(select_box, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        selection_panelLayout.setVerticalGroup(
            selection_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selection_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(select_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(select_ok_button)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        display_panel.setBorder(new javax.swing.border.MatteBorder(null));
        display_panel.setName("display_panel"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel2.setName("jLabel2"); // NOI18N

        display_field.setText(resourceMap.getString("display_field.text")); // NOI18N
        display_field.setBorder(new javax.swing.border.MatteBorder(null));
        display_field.setName("display_field"); // NOI18N

        display_ok_button.setText(resourceMap.getString("display_ok_button.text")); // NOI18N
        display_ok_button.setName("display_ok_button"); // NOI18N
        display_ok_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_ok_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout display_panelLayout = new javax.swing.GroupLayout(display_panel);
        display_panel.setLayout(display_panelLayout);
        display_panelLayout.setHorizontalGroup(
            display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(display_ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display_field, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        display_panelLayout.setVerticalGroup(
            display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(display_field, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(display_ok_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(selection_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(display_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(selection_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(display_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_ok_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_select_ok_buttonMouseClicked
        //selection_panel.setVisible(false);
        if(this.opCode != 3){
            this.setVisible(false);
        }
        String name = select_box.getSelectedItem().toString();
        
        switch(this.opCode){
            case 1:
                cv.setFields(select_box.getSelectedIndex());
                //cv.setFields(select_box.getSelectedIndex());
                cv.setVisible(true);
                break;
            case 2:
                Vector_Storage.removeVector(name);
                break;

            case 3:
                String vector_disp = Vector_Storage.display(name);
                display_field.setText(vector_disp);
                display_panel.setVisible(true);
                break;

        }
}//GEN-LAST:event_select_ok_buttonMouseClicked

    private void display_ok_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_ok_buttonMouseClicked
        this.setVisible(false);
}//GEN-LAST:event_display_ok_buttonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_a_Vector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display_field;
    private javax.swing.JButton display_ok_button;
    private javax.swing.JPanel display_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox select_box;
    private javax.swing.JButton select_ok_button;
    private javax.swing.JPanel selection_panel;
    // End of variables declaration//GEN-END:variables

}
