/*
 * DifferentiationView.java
 */

package differentiation;

import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class DifferentiationView extends FrameView {

    Derivative der = null;
    Integration integration = null;
    String expression = null;
    String compile_msg = null;
    Keyboard keyboard;

    public DifferentiationView(SingleFrameApplication app) {
        super(app);
        initComponents();
        otherInitilization();
        mainPanel.setLayout(new GridBagLayout());

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    public void otherInitilization(){
        
        expression = "";
        der = null;
        compile_msg = "";
        keyboard = new Keyboard();
        no_value.setVisible(false);
        integration = null;
        integration_input.setVisible(false);
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = DifferentiationApp.getApplication().getMainFrame();
            aboutBox = new DifferentiationAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DifferentiationApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        no_input = new javax.swing.JPanel();
        exp_ip = new javax.swing.JButton();
        compile = new javax.swing.JButton();
        diff = new javax.swing.JButton();
        num_diff = new javax.swing.JButton();
        num_inte = new javax.swing.JButton();
        no_value = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        no_value_input = new javax.swing.JFormattedTextField();
        no_input_ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        integration_input = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        integral_lower = new javax.swing.JFormattedTextField();
        integral_upper = new javax.swing.JFormattedTextField();
        integral_ok = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        output_label = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(differentiation.DifferentiationApp.class).getContext().getResourceMap(DifferentiationView.class);
        mainPanel.setBackground(resourceMap.getColor("Calculus.background")); // NOI18N
        mainPanel.setName("Calculus"); // NOI18N

        no_input.setBackground(resourceMap.getColor("no_input.background")); // NOI18N
        no_input.setMaximumSize(new java.awt.Dimension(1500, 900));
        no_input.setMinimumSize(new java.awt.Dimension(1500, 900));
        no_input.setName("no_input"); // NOI18N
        no_input.setPreferredSize(new java.awt.Dimension(1500, 900));

        exp_ip.setIcon(resourceMap.getIcon("exp_ip.icon")); // NOI18N
        exp_ip.setText(resourceMap.getString("exp_ip.text")); // NOI18N
        exp_ip.setToolTipText(resourceMap.getString("exp_ip.toolTipText")); // NOI18N
        exp_ip.setName("exp_ip"); // NOI18N
        exp_ip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exp_ipMouseClicked(evt);
            }
        });

        compile.setIcon(resourceMap.getIcon("compile.icon")); // NOI18N
        compile.setText(resourceMap.getString("compile.text")); // NOI18N
        compile.setToolTipText(resourceMap.getString("compile.toolTipText")); // NOI18N
        compile.setName("compile"); // NOI18N
        compile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compileMouseClicked(evt);
            }
        });

        diff.setBackground(resourceMap.getColor("diff.background")); // NOI18N
        diff.setIcon(resourceMap.getIcon("diff.icon")); // NOI18N
        diff.setText(resourceMap.getString("diff.text")); // NOI18N
        diff.setToolTipText(resourceMap.getString("diff.toolTipText")); // NOI18N
        diff.setName("diff"); // NOI18N
        diff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diffMouseClicked(evt);
            }
        });

        num_diff.setIcon(resourceMap.getIcon("num_diff.icon")); // NOI18N
        num_diff.setText(resourceMap.getString("num_diff.text")); // NOI18N
        num_diff.setToolTipText(resourceMap.getString("num_diff.toolTipText")); // NOI18N
        num_diff.setName("num_diff"); // NOI18N
        num_diff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_diffMouseClicked(evt);
            }
        });

        num_inte.setIcon(resourceMap.getIcon("num_inte.icon")); // NOI18N
        num_inte.setText(resourceMap.getString("num_inte.text")); // NOI18N
        num_inte.setToolTipText(resourceMap.getString("num_inte.toolTipText")); // NOI18N
        num_inte.setName("num_inte"); // NOI18N
        num_inte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_inteMouseClicked(evt);
            }
        });

        no_value.setBackground(resourceMap.getColor("no_value.background")); // NOI18N
        no_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        no_value.setName("no_value"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        no_value_input.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        no_value_input.setText(resourceMap.getString("no_value_input.text")); // NOI18N
        no_value_input.setName("no_value_input"); // NOI18N

        no_input_ok.setIcon(resourceMap.getIcon("no_input_ok.icon")); // NOI18N
        no_input_ok.setText(resourceMap.getString("no_input_ok.text")); // NOI18N
        no_input_ok.setName("no_input_ok"); // NOI18N
        no_input_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                no_input_okMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout no_valueLayout = new javax.swing.GroupLayout(no_value);
        no_value.setLayout(no_valueLayout);
        no_valueLayout.setHorizontalGroup(
            no_valueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no_valueLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(no_value_input, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no_valueLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(no_input_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        no_valueLayout.setVerticalGroup(
            no_valueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_valueLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(no_valueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_value_input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(no_input_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        integration_input.setBackground(resourceMap.getColor("integration_input.background")); // NOI18N
        integration_input.setName("integration_input"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        integral_lower.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        integral_lower.setText(resourceMap.getString("integral_lower.text")); // NOI18N
        integral_lower.setName("integral_lower"); // NOI18N

        integral_upper.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        integral_upper.setText(resourceMap.getString("integral_upper.text")); // NOI18N
        integral_upper.setName("integral_upper"); // NOI18N

        integral_ok.setIcon(resourceMap.getIcon("integral_ok.icon")); // NOI18N
        integral_ok.setText(resourceMap.getString("integral_ok.text")); // NOI18N
        integral_ok.setName("integral_ok"); // NOI18N
        integral_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                integral_okMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout integration_inputLayout = new javax.swing.GroupLayout(integration_input);
        integration_input.setLayout(integration_inputLayout);
        integration_inputLayout.setHorizontalGroup(
            integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integration_inputLayout.createSequentialGroup()
                .addGroup(integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(integration_inputLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addGroup(integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(integral_upper)
                            .addComponent(integral_lower, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                    .addGroup(integration_inputLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(integral_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        integration_inputLayout.setVerticalGroup(
            integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integration_inputLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(integral_lower, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(integration_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(integral_upper, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(integral_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel14.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        output_label.setText(resourceMap.getString("output_label.text")); // NOI18N
        output_label.setName("output_label"); // NOI18N

        javax.swing.GroupLayout no_inputLayout = new javax.swing.GroupLayout(no_input);
        no_input.setLayout(no_inputLayout);
        no_inputLayout.setHorizontalGroup(
            no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_inputLayout.createSequentialGroup()
                .addGroup(no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(no_inputLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(exp_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(compile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(diff)
                            .addComponent(jLabel6)
                            .addComponent(num_diff, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(num_inte, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(no_inputLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(324, 324, 324))
                            .addGroup(no_inputLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(no_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(integration_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(no_inputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(no_inputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(output_label, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        no_inputLayout.setVerticalGroup(
            no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_inputLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(no_inputLayout.createSequentialGroup()
                        .addComponent(exp_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(no_inputLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(no_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(integration_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(no_value, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(no_inputLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(compile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16)
                        .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(num_diff)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(num_inte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(output_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(no_input, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(no_input, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(differentiation.DifferentiationApp.class).getContext().getActionMap(DifferentiationView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 850, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void no_input_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_no_input_okMouseClicked
        no_value.setVisible(false);
        if(!this.compile_msg.equals(Expression.NO_ERROR_MSG)){
            output_label.setText("Can not Differentiate without compilation");
            
        }
        else{
            double value;
            try{
            value = Double.parseDouble(no_value_input.getText());
            if(!compile_msg.equals(Expression.NO_ERROR_MSG)){
                throw new Exception();
            }
            }
            catch(Exception e){
                output_label.setText("Value Entered is illegal");
                return;
            }

            String derivative = der.getderivative();

            Expression exp = new Expression(derivative);
            double derivative_value = exp.getValue(derivative, value);
            output_label.setText("Derivative At x = "+value+" is: "+derivative_value);
        }
}//GEN-LAST:event_no_input_okMouseClicked

    private void num_diffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_diffMouseClicked
        no_value.setVisible(true);
}//GEN-LAST:event_num_diffMouseClicked

    private void diffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diffMouseClicked
        output_label.setText(der.getderivative());
}//GEN-LAST:event_diffMouseClicked

    private void compileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compileMouseClicked
        this.expression = keyboard.getExpression();
        der = new Derivative(expression);

        this.compile_msg = der.compile();

        output_label.setText(compile_msg);
}//GEN-LAST:event_compileMouseClicked

    private void exp_ipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exp_ipMouseClicked
        keyboard.setVisible(true);
}//GEN-LAST:event_exp_ipMouseClicked

    private void integral_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_integral_okMouseClicked

       integration_input.setVisible(false);
       double lower, upper;
       try{
           lower = Double.parseDouble(integral_lower.getText());
           upper = Double.parseDouble(integral_upper.getText());
           if(!compile_msg.equals(Expression.NO_ERROR_MSG)){
               throw new Exception();
           }
       }
       catch(Exception e){
           output_label.setText("value Entered is illegal");
           return;
       }     
       double integration_value = integration.integrate(lower, upper);
       output_label.setText("Integration value is: "+integration_value);
    }//GEN-LAST:event_integral_okMouseClicked

    private void num_inteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_inteMouseClicked
        expression = keyboard.getExpression();
        integration = new Integration(expression);

        compile_msg = integration.compile();
        output_label.setText(compile_msg);
        integration_input.setVisible(true);
    }//GEN-LAST:event_num_inteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compile;
    private javax.swing.JButton diff;
    private javax.swing.JButton exp_ip;
    private javax.swing.JFormattedTextField integral_lower;
    private javax.swing.JButton integral_ok;
    private javax.swing.JFormattedTextField integral_upper;
    private javax.swing.JPanel integration_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel no_input;
    private javax.swing.JButton no_input_ok;
    private javax.swing.JPanel no_value;
    private javax.swing.JFormattedTextField no_value_input;
    private javax.swing.JButton num_diff;
    private javax.swing.JButton num_inte;
    private javax.swing.JTextField output_label;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
