/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Keyboard.java
 *
 * Created on Jul 27, 2009, 10:03:14 AM
 */

package differentiation;

import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author Dinesh
 */
public class Keyboard extends javax.swing.JFrame {

    int key_position = 0;  //....... DEFAULT POSITION OF THE KEY
    String expression;//........ EXPRESSION.

    /** Creates new form Keyboard */
    public Keyboard() {
        initComponents();
        otherInitilization();
    }
    private void otherInitilization(){
        key_position = 0;
        expression = "";
    }

    private void displayMe(String str, int offset){
        expression = input_field.getText();

        if(key_position == 0){
            expression = str + expression;
        }
        else if(key_position == expression.length()){
            expression = expression + str;
        }
        else{
            String temp = new String(expression);
            String temp_1 = temp.substring(key_position);

            temp = new String(temp.substring(0, key_position));

            temp += str;
            temp += temp_1;
            expression = temp;
        }

        key_position += offset;
        input_field.setText(expression+"");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_field = new javax.swing.JTextField();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        cosec = new javax.swing.JButton();
        asin = new javax.swing.JButton();
        acosec = new javax.swing.JButton();
        sec = new javax.swing.JButton();
        acos = new javax.swing.JButton();
        asec = new javax.swing.JButton();
        cot = new javax.swing.JButton();
        atan = new javax.swing.JButton();
        acot = new javax.swing.JButton();
        open_brace3 = new javax.swing.JButton();
        open_brace2 = new javax.swing.JButton();
        open_brace1 = new javax.swing.JButton();
        log = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        var_x = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        const_e = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        power = new javax.swing.JButton();
        close_brace1 = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        four = new javax.swing.JButton();
        one = new javax.swing.JButton();
        close_brace2 = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        five = new javax.swing.JButton();
        two = new javax.swing.JButton();
        close_brace3 = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        six = new javax.swing.JButton();
        three = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        const_pi = new javax.swing.JButton();
        comma = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        space = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(differentiation.DifferentiationApp.class).getContext().getResourceMap(Keyboard.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        input_field.setFont(resourceMap.getFont("input_field.font")); // NOI18N
        input_field.setText(resourceMap.getString("input_field.text")); // NOI18N
        input_field.setName("input_field"); // NOI18N
        input_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_fieldMouseClicked(evt);
            }
        });
        input_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_fieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_fieldKeyTyped(evt);
            }
        });

        sin.setText(resourceMap.getString("sin.text")); // NOI18N
        sin.setName("sin"); // NOI18N
        sin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinMouseClicked(evt);
            }
        });

        cos.setText(resourceMap.getString("cos.text")); // NOI18N
        cos.setName("cos"); // NOI18N
        cos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosMouseClicked(evt);
            }
        });

        tan.setText(resourceMap.getString("tan.text")); // NOI18N
        tan.setName("tan"); // NOI18N
        tan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanMouseClicked(evt);
            }
        });

        cosec.setText(resourceMap.getString("cosec.text")); // NOI18N
        cosec.setName("cosec"); // NOI18N
        cosec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosecMouseClicked(evt);
            }
        });

        asin.setText(resourceMap.getString("asin.text")); // NOI18N
        asin.setName("asin"); // NOI18N
        asin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asinMouseClicked(evt);
            }
        });

        acosec.setText(resourceMap.getString("acosec.text")); // NOI18N
        acosec.setName("acosec"); // NOI18N
        acosec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acosecMouseClicked(evt);
            }
        });

        sec.setText(resourceMap.getString("sec.text")); // NOI18N
        sec.setName("sec"); // NOI18N
        sec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secMouseClicked(evt);
            }
        });

        acos.setText(resourceMap.getString("acos.text")); // NOI18N
        acos.setName("acos"); // NOI18N
        acos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acosMouseClicked(evt);
            }
        });

        asec.setText(resourceMap.getString("asec.text")); // NOI18N
        asec.setName("asec"); // NOI18N
        asec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asecMouseClicked(evt);
            }
        });

        cot.setText(resourceMap.getString("cot.text")); // NOI18N
        cot.setName("cot"); // NOI18N
        cot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cotMouseClicked(evt);
            }
        });

        atan.setText(resourceMap.getString("atan.text")); // NOI18N
        atan.setName("atan"); // NOI18N
        atan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atanMouseClicked(evt);
            }
        });

        acot.setText(resourceMap.getString("acot.text")); // NOI18N
        acot.setName("acot"); // NOI18N
        acot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acotMouseClicked(evt);
            }
        });

        open_brace3.setText(resourceMap.getString("open_brace3.text")); // NOI18N
        open_brace3.setName("open_brace3"); // NOI18N
        open_brace3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_brace3MouseClicked(evt);
            }
        });

        open_brace2.setText(resourceMap.getString("open_brace2.text")); // NOI18N
        open_brace2.setName("open_brace2"); // NOI18N
        open_brace2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_brace2MouseClicked(evt);
            }
        });

        open_brace1.setText(resourceMap.getString("open_brace1.text")); // NOI18N
        open_brace1.setName("open_brace1"); // NOI18N
        open_brace1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_brace1MouseClicked(evt);
            }
        });

        log.setText(resourceMap.getString("log.text")); // NOI18N
        log.setName("log"); // NOI18N
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });

        exp.setText(resourceMap.getString("exp.text")); // NOI18N
        exp.setName("exp"); // NOI18N
        exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expMouseClicked(evt);
            }
        });

        var_x.setText(resourceMap.getString("var_x.text")); // NOI18N
        var_x.setName("var_x"); // NOI18N
        var_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                var_xMouseClicked(evt);
            }
        });

        plus.setText(resourceMap.getString("plus.text")); // NOI18N
        plus.setName("plus"); // NOI18N
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
        });

        multiply.setText(resourceMap.getString("multiply.text")); // NOI18N
        multiply.setName("multiply"); // NOI18N
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyMouseClicked(evt);
            }
        });

        const_e.setText(resourceMap.getString("const_e.text")); // NOI18N
        const_e.setName("const_e"); // NOI18N
        const_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                const_eMouseClicked(evt);
            }
        });

        minus.setText(resourceMap.getString("minus.text")); // NOI18N
        minus.setName("minus"); // NOI18N
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusMouseClicked(evt);
            }
        });

        divide.setText(resourceMap.getString("divide.text")); // NOI18N
        divide.setName("divide"); // NOI18N
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
        });

        power.setText(resourceMap.getString("power.text")); // NOI18N
        power.setName("power"); // NOI18N
        power.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                powerMouseClicked(evt);
            }
        });

        close_brace1.setText(resourceMap.getString("close_brace1.text")); // NOI18N
        close_brace1.setName("close_brace1"); // NOI18N
        close_brace1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_brace1MouseClicked(evt);
            }
        });

        seven.setText(resourceMap.getString("seven.text")); // NOI18N
        seven.setName("seven"); // NOI18N
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });

        four.setText(resourceMap.getString("four.text")); // NOI18N
        four.setName("four"); // NOI18N
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });

        one.setText(resourceMap.getString("one.text")); // NOI18N
        one.setName("one"); // NOI18N
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });

        close_brace2.setText(resourceMap.getString("close_brace2.text")); // NOI18N
        close_brace2.setName("close_brace2"); // NOI18N
        close_brace2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_brace2MouseClicked(evt);
            }
        });

        eight.setText(resourceMap.getString("eight.text")); // NOI18N
        eight.setName("eight"); // NOI18N
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });

        five.setText(resourceMap.getString("five.text")); // NOI18N
        five.setName("five"); // NOI18N
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });

        two.setText(resourceMap.getString("two.text")); // NOI18N
        two.setName("two"); // NOI18N
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });

        close_brace3.setText(resourceMap.getString("close_brace3.text")); // NOI18N
        close_brace3.setName("close_brace3"); // NOI18N
        close_brace3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_brace3MouseClicked(evt);
            }
        });

        nine.setText(resourceMap.getString("nine.text")); // NOI18N
        nine.setName("nine"); // NOI18N
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });

        six.setText(resourceMap.getString("six.text")); // NOI18N
        six.setName("six"); // NOI18N
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });

        three.setText(resourceMap.getString("three.text")); // NOI18N
        three.setName("three"); // NOI18N
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });

        zero.setText(resourceMap.getString("zero.text")); // NOI18N
        zero.setName("zero"); // NOI18N
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });

        dot.setText(resourceMap.getString("dot.text")); // NOI18N
        dot.setName("dot"); // NOI18N
        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotMouseClicked(evt);
            }
        });

        const_pi.setText(resourceMap.getString("const_pi.text")); // NOI18N
        const_pi.setName("const_pi"); // NOI18N
        const_pi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                const_piMouseClicked(evt);
            }
        });

        comma.setText(resourceMap.getString("comma.text")); // NOI18N
        comma.setName("comma"); // NOI18N
        comma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commaMouseClicked(evt);
            }
        });

        clear.setText(resourceMap.getString("clear.text")); // NOI18N
        clear.setName("clear"); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        backspace.setText(resourceMap.getString("backspace.text")); // NOI18N
        backspace.setName("backspace"); // NOI18N
        backspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backspaceMouseClicked(evt);
            }
        });

        ok.setText(resourceMap.getString("ok.text")); // NOI18N
        ok.setName("ok"); // NOI18N
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });

        space.setText(resourceMap.getString("space.text")); // NOI18N
        space.setName("space"); // NOI18N
        space.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spaceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backspace)
                        .addGap(32, 32, 32)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cosec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(asin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(acosec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(asec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(acos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(open_brace3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(close_brace3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                            .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(acot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(atan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(open_brace2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(exp, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(close_brace2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(open_brace1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(power, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(close_brace1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2))))
                                    .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(zero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(one, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(four, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(seven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(const_pi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(two, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(five, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(var_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(const_e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comma, 0, 0, Short.MAX_VALUE)
                                    .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addGap(48, 48, 48)))))
                .addContainerGap(18, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(362, 362, 362))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(backspace))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(open_brace3)
                    .addComponent(const_e)
                    .addComponent(var_x)
                    .addComponent(const_pi)
                    .addComponent(close_brace3)
                    .addComponent(open_brace2)
                    .addComponent(close_brace2)
                    .addComponent(open_brace1)
                    .addComponent(close_brace1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sin)
                    .addComponent(cos)
                    .addComponent(tan)
                    .addComponent(plus)
                    .addComponent(seven)
                    .addComponent(eight)
                    .addComponent(nine)
                    .addComponent(minus)
                    .addComponent(log))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cosec)
                    .addComponent(sec)
                    .addComponent(cot)
                    .addComponent(divide)
                    .addComponent(four)
                    .addComponent(five)
                    .addComponent(six)
                    .addComponent(multiply)
                    .addComponent(exp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asin)
                    .addComponent(acos)
                    .addComponent(atan)
                    .addComponent(power)
                    .addComponent(one)
                    .addComponent(two)
                    .addComponent(three))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acosec)
                    .addComponent(asec)
                    .addComponent(acot)
                    .addComponent(zero)
                    .addComponent(dot)
                    .addComponent(comma)
                    .addComponent(space))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getExpression(){
        return input_field.getText();
    }

    private void input_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_fieldKeyPressed
        int key = evt.getKeyCode();

        switch(key){
            case KeyEvent.VK_LEFT:
                if(key_position >0){
                    --key_position;
                }
                break;

            case KeyEvent.VK_RIGHT:
                if(key_position < input_field.getText().length()){
                    ++key_position;
                }
                break;
        }
        
    }//GEN-LAST:event_input_fieldKeyPressed

    private void input_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_fieldKeyTyped
        ++key_position;
    }//GEN-LAST:event_input_fieldKeyTyped

    private void input_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_fieldMouseClicked
        key_position = expression.length();
        
    }//GEN-LAST:event_input_fieldMouseClicked

    private void open_brace3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_brace3MouseClicked
        displayMe("{", 1);
}//GEN-LAST:event_open_brace3MouseClicked

    private void open_brace2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_brace2MouseClicked
        displayMe("[", 1);
    }//GEN-LAST:event_open_brace2MouseClicked

    private void open_brace1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_brace1MouseClicked
       displayMe("(", 1);
    }//GEN-LAST:event_open_brace1MouseClicked

    private void close_brace1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_brace1MouseClicked
       displayMe(")", 1);
    }//GEN-LAST:event_close_brace1MouseClicked

    private void close_brace2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_brace2MouseClicked
       displayMe("]", 1);
    }//GEN-LAST:event_close_brace2MouseClicked

    private void close_brace3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_brace3MouseClicked
       displayMe("}", 1);
    }//GEN-LAST:event_close_brace3MouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
       displayMe("7", 1);
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
       displayMe("8", 1);
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
       displayMe("9", 1);
    }//GEN-LAST:event_nineMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
       displayMe("6", 1);
    }//GEN-LAST:event_sixMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
      displayMe("5", 1);
    }//GEN-LAST:event_fiveMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
       displayMe("4", 1);
    }//GEN-LAST:event_fourMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
      displayMe("3", 1);
    }//GEN-LAST:event_threeMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
       displayMe("2", 1);
    }//GEN-LAST:event_twoMouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
       displayMe("1", 1);
    }//GEN-LAST:event_oneMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        displayMe("0", 1);
    }//GEN-LAST:event_zeroMouseClicked

    private void dotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseClicked
       displayMe(".", 1);
    }//GEN-LAST:event_dotMouseClicked

    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked
       displayMe("+", 1);
    }//GEN-LAST:event_plusMouseClicked

    private void minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseClicked
       displayMe("-", 1);
    }//GEN-LAST:event_minusMouseClicked

    private void multiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseClicked
       displayMe("*", 1);
    }//GEN-LAST:event_multiplyMouseClicked

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
        displayMe("/", 1);
    }//GEN-LAST:event_divideMouseClicked

    private void powerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powerMouseClicked
       displayMe("^", 1);
    }//GEN-LAST:event_powerMouseClicked

    private void const_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_const_eMouseClicked
       displayMe("E", 1);
    }//GEN-LAST:event_const_eMouseClicked

    private void var_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_var_xMouseClicked
       displayMe("x", 1);
    }//GEN-LAST:event_var_xMouseClicked

    private void const_piMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_const_piMouseClicked
        displayMe("PI", 2);
    }//GEN-LAST:event_const_piMouseClicked

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
        displayMe("Log(", 4);
    }//GEN-LAST:event_logMouseClicked

    private void expMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expMouseClicked
       displayMe("Exp(", 4);
    }//GEN-LAST:event_expMouseClicked

    private void tanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanMouseClicked
        displayMe("Tan(", 4);
    }//GEN-LAST:event_tanMouseClicked

    private void cosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosMouseClicked
        displayMe("Cos(", 4);
    }//GEN-LAST:event_cosMouseClicked

    private void sinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinMouseClicked
        displayMe("Sin(", 4);
    }//GEN-LAST:event_sinMouseClicked

    private void cotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotMouseClicked
       displayMe("Cot(", 4);
    }//GEN-LAST:event_cotMouseClicked

    private void secMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secMouseClicked
       displayMe("Sec(", 4);
    }//GEN-LAST:event_secMouseClicked

    private void cosecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosecMouseClicked
        displayMe("Cosec(", 6);
    }//GEN-LAST:event_cosecMouseClicked

    private void atanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atanMouseClicked
        displayMe("ATan(", 5);
    }//GEN-LAST:event_atanMouseClicked

    private void acosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acosMouseClicked
        displayMe("ACos(", 5);
    }//GEN-LAST:event_acosMouseClicked

    private void asinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asinMouseClicked
        displayMe("ASin(", 5);
    }//GEN-LAST:event_asinMouseClicked

    private void acotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acotMouseClicked
        displayMe("ACot(", 5);
    }//GEN-LAST:event_acotMouseClicked

    private void asecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asecMouseClicked
        displayMe("ASec(", 5);
    }//GEN-LAST:event_asecMouseClicked

    private void acosecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acosecMouseClicked
       displayMe("ACosec(", 7);
    }//GEN-LAST:event_acosecMouseClicked

    private void commaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commaMouseClicked
        displayMe(",", 1);
    }//GEN-LAST:event_commaMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        input_field.setText("");
        key_position = 0;
    }//GEN-LAST:event_clearMouseClicked

    private void backspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspaceMouseClicked
        if(key_position > 0){
            StringBuffer temp = new StringBuffer(expression);

            temp.deleteCharAt(key_position-1);
            expression = temp.toString();

            input_field.setText(expression);
            --key_position;
        }
    }//GEN-LAST:event_backspaceMouseClicked

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        this.setVisible(false);
}//GEN-LAST:event_okMouseClicked

    private void spaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spaceMouseClicked
        displayMe(" ", 1);
    }//GEN-LAST:event_spaceMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keyboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acos;
    private javax.swing.JButton acosec;
    private javax.swing.JButton acot;
    private javax.swing.JButton asec;
    private javax.swing.JButton asin;
    private javax.swing.JButton atan;
    private javax.swing.JButton backspace;
    private javax.swing.JButton clear;
    private javax.swing.JButton close_brace1;
    private javax.swing.JButton close_brace2;
    private javax.swing.JButton close_brace3;
    private javax.swing.JButton comma;
    private javax.swing.JButton const_e;
    private javax.swing.JButton const_pi;
    private javax.swing.JButton cos;
    private javax.swing.JButton cosec;
    private javax.swing.JButton cot;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton exp;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JTextField input_field;
    private javax.swing.JButton log;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton ok;
    private javax.swing.JButton one;
    private javax.swing.JButton open_brace1;
    private javax.swing.JButton open_brace2;
    private javax.swing.JButton open_brace3;
    private javax.swing.JButton plus;
    private javax.swing.JButton power;
    private javax.swing.JButton sec;
    private javax.swing.JButton seven;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton space;
    private javax.swing.JButton tan;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton var_x;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables

}
