/*
 * Calci_pgView.java
 */

package calci_pg;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class Calci_pgView extends FrameView {

    public Calci_pgView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = Calci_pgApp.getApplication().getMainFrame();
            aboutBox = new Calci_pgAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        Calci_pgApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        plus_but = new javax.swing.JButton();
        nine_but = new javax.swing.JButton();
        one_but = new javax.swing.JButton();
        four_but = new javax.swing.JButton();
        seven_but = new javax.swing.JButton();
        decimal_but = new javax.swing.JButton();
        two_but = new javax.swing.JButton();
        five_but = new javax.swing.JButton();
        eight_but = new javax.swing.JButton();
        comma_but = new javax.swing.JButton();
        three_but = new javax.swing.JButton();
        divide_but = new javax.swing.JButton();
        mul_but = new javax.swing.JButton();
        six_but = new javax.swing.JButton();
        minus_but = new javax.swing.JButton();
        power_but = new javax.swing.JButton();
        ln_but = new javax.swing.JButton();
        log_but = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        atan_but = new javax.swing.JButton();
        acos_but = new javax.swing.JButton();
        asin_but = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        tan_but = new javax.swing.JButton();
        cos_but = new javax.swing.JButton();
        sine_but = new javax.swing.JButton();
        zero_but = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        backspace_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        output = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(calci_pg.Calci_pgApp.class).getContext().getResourceMap(Calci_pgView.class);
        input.setText(resourceMap.getString("input.text")); // NOI18N
        input.setName("input"); // NOI18N

        plus_but.setText(resourceMap.getString("plus_but.text")); // NOI18N
        plus_but.setName("plus_but"); // NOI18N
        plus_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus_butMouseClicked(evt);
            }
        });

        nine_but.setText(resourceMap.getString("nine_but.text")); // NOI18N
        nine_but.setName("nine_but"); // NOI18N
        nine_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nine_butMouseClicked(evt);
            }
        });

        one_but.setText(resourceMap.getString("one_but.text")); // NOI18N
        one_but.setName("one_but"); // NOI18N
        one_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                one_butMouseClicked(evt);
            }
        });

        four_but.setText(resourceMap.getString("four_but.text")); // NOI18N
        four_but.setName("four_but"); // NOI18N
        four_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                four_butMouseClicked(evt);
            }
        });

        seven_but.setText(resourceMap.getString("seven_but.text")); // NOI18N
        seven_but.setName("seven_but"); // NOI18N
        seven_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seven_butMouseClicked(evt);
            }
        });

        decimal_but.setText(resourceMap.getString("decimal_but.text")); // NOI18N
        decimal_but.setName("decimal_but"); // NOI18N
        decimal_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decimal_butMouseClicked(evt);
            }
        });

        two_but.setText(resourceMap.getString("two_but.text")); // NOI18N
        two_but.setName("two_but"); // NOI18N
        two_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                two_butMouseClicked(evt);
            }
        });

        five_but.setText(resourceMap.getString("five_but.text")); // NOI18N
        five_but.setName("five_but"); // NOI18N
        five_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                five_butMouseClicked(evt);
            }
        });

        eight_but.setText(resourceMap.getString("eight_but.text")); // NOI18N
        eight_but.setName("eight_but"); // NOI18N
        eight_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eight_butMouseClicked(evt);
            }
        });

        comma_but.setText(resourceMap.getString("comma_but.text")); // NOI18N
        comma_but.setName("comma_but"); // NOI18N
        comma_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comma_butMouseClicked(evt);
            }
        });

        three_but.setText(resourceMap.getString("three_but.text")); // NOI18N
        three_but.setName("three_but"); // NOI18N
        three_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                three_butMouseClicked(evt);
            }
        });

        divide_but.setText(resourceMap.getString("divide_but.text")); // NOI18N
        divide_but.setName("divide_but"); // NOI18N
        divide_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divide_butMouseClicked(evt);
            }
        });

        mul_but.setText(resourceMap.getString("mul_but.text")); // NOI18N
        mul_but.setName("mul_but"); // NOI18N
        mul_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mul_butMouseClicked(evt);
            }
        });

        six_but.setText(resourceMap.getString("six_but.text")); // NOI18N
        six_but.setName("six_but"); // NOI18N
        six_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                six_butMouseClicked(evt);
            }
        });

        minus_but.setText(resourceMap.getString("minus_but.text")); // NOI18N
        minus_but.setName("minus_but"); // NOI18N
        minus_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_butMouseClicked(evt);
            }
        });

        power_but.setText(resourceMap.getString("power_but.text")); // NOI18N
        power_but.setName("power_but"); // NOI18N
        power_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                power_butMouseClicked(evt);
            }
        });

        ln_but.setText(resourceMap.getString("ln_but.text")); // NOI18N
        ln_but.setName("ln_but"); // NOI18N
        ln_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ln_butMouseClicked(evt);
            }
        });

        log_but.setText(resourceMap.getString("log_but.text")); // NOI18N
        log_but.setName("log_but"); // NOI18N
        log_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_butMouseClicked(evt);
            }
        });

        jButton19.setText(resourceMap.getString("jButton19.text")); // NOI18N
        jButton19.setName("jButton19"); // NOI18N
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });

        atan_but.setText(resourceMap.getString("atan_but.text")); // NOI18N
        atan_but.setName("atan_but"); // NOI18N
        atan_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atan_butMouseClicked(evt);
            }
        });

        acos_but.setText(resourceMap.getString("acos_but.text")); // NOI18N
        acos_but.setName("acos_but"); // NOI18N
        acos_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acos_butMouseClicked(evt);
            }
        });

        asin_but.setText(resourceMap.getString("asin_but.text")); // NOI18N
        asin_but.setName("asin_but"); // NOI18N
        asin_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asin_butMouseClicked(evt);
            }
        });

        jButton23.setText(resourceMap.getString("jButton23.text")); // NOI18N
        jButton23.setName("jButton23"); // NOI18N
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });

        tan_but.setText(resourceMap.getString("tan_but.text")); // NOI18N
        tan_but.setName("tan_but"); // NOI18N
        tan_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tan_butMouseClicked(evt);
            }
        });

        cos_but.setText(resourceMap.getString("cos_but.text")); // NOI18N
        cos_but.setName("cos_but"); // NOI18N
        cos_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cos_butMouseClicked(evt);
            }
        });

        sine_but.setText(resourceMap.getString("sine_but.text")); // NOI18N
        sine_but.setName("sine_but"); // NOI18N
        sine_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sine_butMouseClicked(evt);
            }
        });

        zero_but.setText(resourceMap.getString("zero_but.text")); // NOI18N
        zero_but.setName("zero_but"); // NOI18N
        zero_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zero_butMouseClicked(evt);
            }
        });

        jButton28.setText(resourceMap.getString("jButton28.text")); // NOI18N
        jButton28.setName("jButton28"); // NOI18N
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });

        jButton20.setText(resourceMap.getString("jButton20.text")); // NOI18N
        jButton20.setName("jButton20"); // NOI18N
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });

        jButton21.setText(resourceMap.getString("jButton21.text")); // NOI18N
        jButton21.setName("jButton21"); // NOI18N
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });

        clear_button.setText(resourceMap.getString("clear_button.text")); // NOI18N
        clear_button.setName("clear_button"); // NOI18N
        clear_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_buttonMouseClicked(evt);
            }
        });

        backspace_button.setText(resourceMap.getString("backspace_button.text")); // NOI18N
        backspace_button.setName("backspace_button"); // NOI18N
        backspace_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backspace_buttonMouseClicked(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        output.setText(resourceMap.getString("output.text")); // NOI18N
        output.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        output.setName("output"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clear_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backspace_button, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ln_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(log_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(power_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seven_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(four_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zero_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(five_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(two_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eight_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nine_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(six_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(three_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(decimal_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comma_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sine_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cos_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tan_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asin_but, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(acos_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atan_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plus_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mul_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divide_but, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(496, 496, 496))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(asin_but)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cos_but)
                            .addComponent(acos_but))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tan_but)
                            .addComponent(atan_but)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backspace_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seven_but)
                                    .addComponent(nine_but)
                                    .addComponent(eight_but)
                                    .addComponent(log_but)
                                    .addComponent(jButton21)
                                    .addComponent(sine_but)
                                    .addComponent(plus_but))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(four_but)
                                            .addComponent(five_but)
                                            .addComponent(six_but)
                                            .addComponent(ln_but)
                                            .addComponent(jButton20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(one_but)
                                            .addComponent(two_but)
                                            .addComponent(three_but)
                                            .addComponent(power_but)
                                            .addComponent(jButton19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(zero_but)
                                            .addComponent(decimal_but)
                                            .addComponent(comma_but)
                                            .addComponent(jButton28)
                                            .addComponent(jButton23)))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(minus_but)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mul_but)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(divide_but)))))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(calci_pg.Calci_pgApp.class).getContext().getActionMap(Calci_pgView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 907, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void plus_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus_butMouseClicked
        String temp = input.getText();
        temp = temp + "+";
        input.setText(temp);
    }//GEN-LAST:event_plus_butMouseClicked

    private void minus_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_butMouseClicked
        String temp = input.getText();
        temp = temp + "-";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_minus_butMouseClicked

    private void mul_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mul_butMouseClicked
        String temp = input.getText();
        temp = temp + "*";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_mul_butMouseClicked

    private void divide_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divide_butMouseClicked
        String temp = input.getText();
        temp = temp + "/";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_divide_butMouseClicked

    private void nine_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nine_butMouseClicked
         String temp = input.getText();
        temp = temp + "9";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_nine_butMouseClicked

    private void six_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_six_butMouseClicked
         String temp = input.getText();
        temp = temp + "6";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_six_butMouseClicked

    private void three_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_three_butMouseClicked
         String temp = input.getText();
        temp = temp + "3";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_three_butMouseClicked

    private void eight_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eight_butMouseClicked
        String temp = input.getText();
        temp = temp + "8";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_eight_butMouseClicked

    private void five_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_five_butMouseClicked
        String temp = input.getText();
        temp = temp + "5";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_five_butMouseClicked

    private void two_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_butMouseClicked
        String temp = input.getText();
        temp = temp + "2";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_two_butMouseClicked

    private void decimal_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimal_butMouseClicked
        String temp = input.getText();
        temp = temp + ".";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_decimal_butMouseClicked

    private void seven_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seven_butMouseClicked
        String temp = input.getText();
        temp = temp + "7";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_seven_butMouseClicked

    private void four_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_four_butMouseClicked
        String temp = input.getText();
        temp = temp + "4";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_four_butMouseClicked

    private void one_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one_butMouseClicked
        String temp = input.getText();
        temp = temp + "1";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_one_butMouseClicked

    private void zero_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zero_butMouseClicked
        String temp = input.getText();
        temp = temp + "0";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_zero_butMouseClicked

    private void sine_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sine_butMouseClicked
        String temp = input.getText();
        temp = temp + "Sin(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_sine_butMouseClicked

    private void cos_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cos_butMouseClicked
        String temp = input.getText();
        temp = temp + "cos(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_cos_butMouseClicked

    private void tan_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tan_butMouseClicked
        String temp = input.getText();
        temp = temp + "tan(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_tan_butMouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        String temp = input.getText();
        temp = temp + ")";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseClicked

    private void asin_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asin_butMouseClicked
        String temp = input.getText();
        temp = temp + "asin(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_asin_butMouseClicked

    private void acos_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acos_butMouseClicked
        String temp = input.getText();
        temp = temp + "acos(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_acos_butMouseClicked

    private void atan_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atan_butMouseClicked
        String temp = input.getText();
        temp = temp + "atan(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_atan_butMouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        String temp = input.getText();
        temp = temp + "(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19MouseClicked

    private void log_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_butMouseClicked
        String temp = input.getText();
        temp = temp + "log(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_log_butMouseClicked

    private void ln_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ln_butMouseClicked
        String temp = input.getText();
        temp = temp + "ln(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_ln_butMouseClicked

    private void power_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_power_butMouseClicked
        String temp = input.getText();
        temp = temp + "^";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_power_butMouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        String temp = input.getText();
        temp = temp + "exp(";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        String temp = input.getText();
        temp = temp + "]";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        String temp = input.getText();
        temp = temp + "[";
        input.setText(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseClicked

    private void clear_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_buttonMouseClicked
        input.setText(" ");        // TODO add your handling code here:
}//GEN-LAST:event_clear_buttonMouseClicked

    private void backspace_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspace_buttonMouseClicked
      String s = input.getText();
      if(s.length() == 0 || s == null){
          return; //... what to do for null text or no text
      }
      s = new StringBuffer(s).substring(0, s.length()-1).toString();
      input.setText(s);
}//GEN-LAST:event_backspace_buttonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String msg = "[" + input.getText() + "]";
        Expression exp = new Expression(msg);
        if(exp.compile().equals(Expression.NO_ERROR_MSG)){
            output.setText(Double.toString(exp.getValue(msg, 0)));
        }
        else{
            output.setText("Incorrect input");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void comma_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comma_butMouseClicked
        String temp = input.getText();
        temp = temp + ",";
        input.setText(temp);    // TODO add your handling code here:
    }//GEN-LAST:event_comma_butMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acos_but;
    private javax.swing.JButton asin_but;
    private javax.swing.JButton atan_but;
    private javax.swing.JButton backspace_button;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton comma_but;
    private javax.swing.JButton cos_but;
    private javax.swing.JButton decimal_but;
    private javax.swing.JButton divide_but;
    private javax.swing.JButton eight_but;
    private javax.swing.JButton five_but;
    private javax.swing.JButton four_but;
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton ln_but;
    private javax.swing.JButton log_but;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton minus_but;
    private javax.swing.JButton mul_but;
    private javax.swing.JButton nine_but;
    private javax.swing.JButton one_but;
    private javax.swing.JLabel output;
    private javax.swing.JButton plus_but;
    private javax.swing.JButton power_but;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton seven_but;
    private javax.swing.JButton sine_but;
    private javax.swing.JButton six_but;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton tan_but;
    private javax.swing.JButton three_but;
    private javax.swing.JButton two_but;
    private javax.swing.JButton zero_but;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
