/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Set_path.java
 *
 * Created on Aug 8, 2009, 6:33:31 AM
 */

package mathworld;
import java.io.*;
/**
 *
 * @author Dinesh
 */
public class Set_path extends javax.swing.JFrame {

    /** Creates new form Set_path */
    public Set_path() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        path = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mathworld.MathworldApp.class).getContext().getResourceMap(Set_path.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        path.setText(resourceMap.getString("path.text")); // NOI18N
        path.setName("path"); // NOI18N

        ok.setText(resourceMap.getString("ok.text")); // NOI18N
        ok.setName("ok"); // NOI18N
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ok)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
                FileOutputStream out; // declare a file output object
                PrintStream p; // declare a print stream object

                try
                {
                        // Create a new file output stream
                        // connected to "myfile.txt"
                        out = new FileOutputStream("LaunchCalculus.bat");
                         
                        // Connect print stream to the output stream
                        p = new PrintStream( out );

                        p.println ("cd Calculus");
                        p.println("set path="+path.getText());
                        p.println("java -jar \"Calculus.jar\"");
                        p.println("exit");

                        p.close();

                              out = new FileOutputStream("LaunchExpression_Evaluater.bat");

                        // Connect print stream to the output stream
                        p = new PrintStream( out );

                        p.println ("cd Expression_Evaluater");
                        p.println("set path="+path.getText());
                        p.println("java -jar \"Expression_Evaluater.jar\"");
                        p.println("exit");

                        p.close();

                              out = new FileOutputStream("LaunchMatrix_Solver.bat");

                        // Connect print stream to the output stream
                        p = new PrintStream( out );

                        p.println ("cd Matrix_Solver");
                        p.println("set path="+path.getText());
                        p.println("java -jar \"Matrix_Solver.jar\"");
                        p.println("exit");

                        p.close();

                              out = new FileOutputStream("LaunchNon_Linear_Equation_Solver.bat");

                        // Connect print stream to the output stream
                        p = new PrintStream( out );

                        p.println ("cd Non_Linear_Equation_Solver");
                        p.println("set path="+path.getText());
                        p.println("java -jar \"Non_Linear_Equation_Solver.jar\"");
                        p.println("exit");

                        p.close();

                              out = new FileOutputStream("LaunchSimultaneous_solver.bat");

                        // Connect print stream to the output stream
                        p = new PrintStream( out );

                        p.println ("cd Simultaneous_solver");
                        p.println("set path="+path.getText());
                        p.println("java -jar \"Simultaneous_solver.jar\"");
                        p.println("exit");

                        p.close();
                }
                catch (Exception e)
                {
                        System.err.println ("Error writing to file");
                }
             this.setVisible(false);
    }//GEN-LAST:event_okMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Set_path().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField path;
    // End of variables declaration//GEN-END:variables

}
