/*
 * Simultaneous_solverView.java
 */

package simultaneous_solver;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class Simultaneous_solverView extends FrameView {

    private int no_of_unknown; //.......... USED TO STORE NO. OF UNKNOWN..
    private int no_of_entry; //............ KEEPS TRACK OF NUMBER OF INPUT...

    private Double[][] user_input_A;  //.....  AN ARRAY KEEPS TRACK OF USER INPUT IN THE COE BOX.
    private Double[] user_input_C; //....... AN ARRAY KEEPS THE MULIPLICAND IN INPUT FORM...
    
    private Matrix matrixA; //................. EQUATION IS OF FORM OF::
    private Matrix matrixB; //................. A.B = C
    private Matrix matrixC;
    
    public Simultaneous_solverView(SingleFrameApplication app) {
        super(app);

        initComponents();
        otherInitilization();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    public void otherInitilization(){
        output_panel.setVisible(false);
        eq_entry_panel.setVisible(false);
        no_of_unknown_panel.setVisible(true);

        no_of_unknown = 0;
        no_of_entry = 0;

        matrixA = null;
        matrixB = null;
        matrixC = null;
    }
    
    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = Simultaneous_solverApp.getApplication().getMainFrame();
            aboutBox = new Simultaneous_solverAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        Simultaneous_solverApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        no_of_unknown_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        no_of_unknown_ok = new javax.swing.JButton();
        no_of_unknown_value = new javax.swing.JComboBox();
        output_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        output_label = new javax.swing.JLabel();
        output_done = new javax.swing.JButton();
        eq_entry_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        eq_entry_next = new javax.swing.JButton();
        eq_entry_previous = new javax.swing.JButton();
        eq_entry_cancel = new javax.swing.JButton();
        coe_1 = new javax.swing.JFormattedTextField();
        coe_2 = new javax.swing.JFormattedTextField();
        coe_3 = new javax.swing.JFormattedTextField();
        coe_4 = new javax.swing.JFormattedTextField();
        coe_5 = new javax.swing.JFormattedTextField();
        coe_6 = new javax.swing.JFormattedTextField();
        coe_7 = new javax.swing.JFormattedTextField();
        coe_8 = new javax.swing.JFormattedTextField();
        coe_9 = new javax.swing.JFormattedTextField();
        coe_10 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        coe_multi = new javax.swing.JFormattedTextField();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(simultaneous_solver.Simultaneous_solverApp.class).getContext().getResourceMap(Simultaneous_solverView.class);
        mainPanel.setBackground(resourceMap.getColor("mainPanel.background")); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setName("jPanel1"); // NOI18N

        no_of_unknown_panel.setBackground(resourceMap.getColor("no_of_unknown_panel.background")); // NOI18N
        no_of_unknown_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        no_of_unknown_panel.setName("no_of_unknown_panel"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setName("jLabel1"); // NOI18N

        no_of_unknown_ok.setText(resourceMap.getString("no_of_unknown_ok.text")); // NOI18N
        no_of_unknown_ok.setName("no_of_unknown_ok"); // NOI18N
        no_of_unknown_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                no_of_unknown_okMouseClicked(evt);
            }
        });

        no_of_unknown_value.setFont(resourceMap.getFont("no_of_unknown_value.font")); // NOI18N
        no_of_unknown_value.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        no_of_unknown_value.setName("no_of_unknown_value"); // NOI18N

        javax.swing.GroupLayout no_of_unknown_panelLayout = new javax.swing.GroupLayout(no_of_unknown_panel);
        no_of_unknown_panel.setLayout(no_of_unknown_panelLayout);
        no_of_unknown_panelLayout.setHorizontalGroup(
            no_of_unknown_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_of_unknown_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(no_of_unknown_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(no_of_unknown_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(no_of_unknown_value, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        no_of_unknown_panelLayout.setVerticalGroup(
            no_of_unknown_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_of_unknown_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(no_of_unknown_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_of_unknown_value, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(no_of_unknown_ok)
                .addGap(30, 30, 30))
        );

        output_panel.setBackground(resourceMap.getColor("output_panel.background")); // NOI18N
        output_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        output_panel.setName("output_panel"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel2.setName("jLabel2"); // NOI18N

        output_label.setFont(resourceMap.getFont("output_label.font")); // NOI18N
        output_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        output_label.setText(resourceMap.getString("output_label.text")); // NOI18N
        output_label.setBorder(new javax.swing.border.MatteBorder(null));
        output_label.setName("output_label"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(simultaneous_solver.Simultaneous_solverApp.class).getContext().getActionMap(Simultaneous_solverView.class, this);
        output_done.setAction(actionMap.get("quit")); // NOI18N
        output_done.setText(resourceMap.getString("output_done.text")); // NOI18N
        output_done.setName("output_done"); // NOI18N

        javax.swing.GroupLayout output_panelLayout = new javax.swing.GroupLayout(output_panel);
        output_panel.setLayout(output_panelLayout);
        output_panelLayout.setHorizontalGroup(
            output_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(output_panelLayout.createSequentialGroup()
                .addGroup(output_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(output_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(output_panelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(output_done, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(output_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(output_label, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                .addContainerGap())
        );
        output_panelLayout.setVerticalGroup(
            output_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(output_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output_label, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(output_done)
                .addContainerGap())
        );

        eq_entry_panel.setBackground(resourceMap.getColor("eq_entry_panel.background")); // NOI18N
        eq_entry_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eq_entry_panel.setName("eq_entry_panel"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel4.setName("jLabel4"); // NOI18N

        eq_entry_next.setText(resourceMap.getString("eq_entry_next.text")); // NOI18N
        eq_entry_next.setName("eq_entry_next"); // NOI18N
        eq_entry_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eq_entry_nextMouseClicked(evt);
            }
        });

        eq_entry_previous.setText(resourceMap.getString("eq_entry_previous.text")); // NOI18N
        eq_entry_previous.setName("eq_entry_previous"); // NOI18N
        eq_entry_previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eq_entry_previousMouseClicked(evt);
            }
        });

        eq_entry_cancel.setText(resourceMap.getString("eq_entry_cancel.text")); // NOI18N
        eq_entry_cancel.setName("eq_entry_cancel"); // NOI18N
        eq_entry_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eq_entry_cancelMouseClicked(evt);
            }
        });

        coe_1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_1.setText(resourceMap.getString("coe_1.text")); // NOI18N
        coe_1.setName("coe_1"); // NOI18N

        coe_2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_2.setText(resourceMap.getString("coe_2.text")); // NOI18N
        coe_2.setName("coe_2"); // NOI18N

        coe_3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_3.setText(resourceMap.getString("coe_3.text")); // NOI18N
        coe_3.setName("coe_3"); // NOI18N

        coe_4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_4.setText(resourceMap.getString("coe_4.text")); // NOI18N
        coe_4.setName("coe_4"); // NOI18N

        coe_5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_5.setText(resourceMap.getString("coe_5.text")); // NOI18N
        coe_5.setName("coe_5"); // NOI18N

        coe_6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_6.setText(resourceMap.getString("coe_6.text")); // NOI18N
        coe_6.setName("coe_6"); // NOI18N

        coe_7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_7.setText(resourceMap.getString("coe_7.text")); // NOI18N
        coe_7.setName("coe_7"); // NOI18N

        coe_8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_8.setText(resourceMap.getString("coe_8.text")); // NOI18N
        coe_8.setName("coe_8"); // NOI18N

        coe_9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_9.setText(resourceMap.getString("coe_9.text")); // NOI18N
        coe_9.setName("coe_9"); // NOI18N

        coe_10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_10.setText(resourceMap.getString("coe_10.text")); // NOI18N
        coe_10.setName("coe_10"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel5.setName("jLabel5"); // NOI18N

        coe_multi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        coe_multi.setText(resourceMap.getString("coe_multi.text")); // NOI18N
        coe_multi.setName("coe_multi"); // NOI18N

        javax.swing.GroupLayout eq_entry_panelLayout = new javax.swing.GroupLayout(eq_entry_panel);
        eq_entry_panel.setLayout(eq_entry_panelLayout);
        eq_entry_panelLayout.setHorizontalGroup(
            eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eq_entry_panelLayout.createSequentialGroup()
                .addGroup(eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eq_entry_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(coe_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eq_entry_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eq_entry_next, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eq_entry_panelLayout.createSequentialGroup()
                        .addGroup(eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eq_entry_panelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(eq_entry_panelLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(eq_entry_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(eq_entry_cancel))
                    .addGroup(eq_entry_panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(coe_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coe_10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coe_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        eq_entry_panelLayout.setVerticalGroup(
            eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eq_entry_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(coe_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coe_6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(coe_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coe_1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(coe_4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(eq_entry_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(eq_entry_cancel)
                    .addComponent(eq_entry_previous)
                    .addComponent(eq_entry_next))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(eq_entry_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_of_unknown_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(output_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eq_entry_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(no_of_unknown_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(output_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 851, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void no_of_unknown_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_no_of_unknown_okMouseClicked
        no_of_unknown_panel.setVisible(false);

        no_of_unknown = Integer.parseInt(no_of_unknown_value.getSelectedItem().toString());

        matrixA = new Matrix(no_of_unknown, no_of_unknown);
        user_input_A = new Double[no_of_unknown][no_of_unknown];

        matrixC = new Matrix(no_of_unknown, 1);
        user_input_C = new Double[no_of_unknown];
        
        set_eq_entry_panel();

        for(int i=0 ; i<no_of_unknown ; ++i){
            for(int j=0 ; j<no_of_unknown ; ++j){
                user_input_A[i][j] = 0.0;
            }
            user_input_C[i] = 0.0;
        }
        eq_entry_panel.setVisible(true);
    }//GEN-LAST:event_no_of_unknown_okMouseClicked

    private void eq_entry_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eq_entry_nextMouseClicked
        if(no_of_entry < no_of_unknown){
            try{
                getInput();
            }
            catch(Exception e){
                return;
            }
            ++no_of_entry;
        }

        if(no_of_entry == no_of_unknown){
            eq_entry_panel.setVisible(false);
            getSolution();
            output_panel.setVisible(true);
        }
        else{
            set_eq_entry_panel_fields(); //.......  DO THIS ONLY IF ITS NOT THE LAST THING...
        }
    }//GEN-LAST:event_eq_entry_nextMouseClicked

    private void eq_entry_previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eq_entry_previousMouseClicked
       if(no_of_entry <= 0){
           return;
       }
       --no_of_entry;
       set_eq_entry_panel_fields();
    }//GEN-LAST:event_eq_entry_previousMouseClicked

    private void eq_entry_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eq_entry_cancelMouseClicked
        eq_entry_panel.setVisible(false);
        no_of_unknown_panel.setVisible(true);
    }//GEN-LAST:event_eq_entry_cancelMouseClicked

    public void getInput()throws Exception{

        if(no_of_unknown >=1 ){
            user_input_A[no_of_entry][0] = Double.parseDouble(coe_1.getText());
            matrixA.setElement(user_input_A[no_of_entry][0], no_of_entry, 0);
        }
        if(no_of_unknown >=2 ){
            user_input_A[no_of_entry][1] = Double.parseDouble(coe_2.getText());
            matrixA.setElement(user_input_A[no_of_entry][1], no_of_entry, 1);
        }
        if(no_of_unknown >=3 ){
            user_input_A[no_of_entry][2] = Double.parseDouble(coe_3.getText());
            matrixA.setElement(user_input_A[no_of_entry][2], no_of_entry, 2);
        }
        if(no_of_unknown >=4 ){
            user_input_A[no_of_entry][3] = Double.parseDouble(coe_4.getText());
            matrixA.setElement(user_input_A[no_of_entry][3], no_of_entry, 3);
        }
        if(no_of_unknown >=5 ){
            user_input_A[no_of_entry][4] = Double.parseDouble(coe_5.getText());
            matrixA.setElement(user_input_A[no_of_entry][4], no_of_entry, 4);
        }
        if(no_of_unknown >= 6 ){
            user_input_A[no_of_entry][5] = Double.parseDouble(coe_6.getText());
            matrixA.setElement(user_input_A[no_of_entry][5], no_of_entry, 5);
        }
        if(no_of_unknown >= 7 ){
            user_input_A[no_of_entry][6] = Double.parseDouble(coe_7.getText());
            matrixA.setElement(user_input_A[no_of_entry][6], no_of_entry, 6);
        }
        if(no_of_unknown >= 8 ){
            user_input_A[no_of_entry][7] = Double.parseDouble(coe_8.getText());
            matrixA.setElement(user_input_A[no_of_entry][7], no_of_entry, 7);
        }
        if(no_of_unknown >= 9 ){
            user_input_A[no_of_entry][8] = Double.parseDouble(coe_9.getText());
            matrixA.setElement(user_input_A[no_of_entry][8], no_of_entry, 8);
        }
        if(no_of_unknown >= 10){
            user_input_A[no_of_entry][9] = Double.parseDouble(coe_10.getText());
            matrixA.setElement(user_input_A[no_of_entry][9], no_of_entry, 9);
        }

        user_input_C[no_of_entry]    = Double.parseDouble(coe_multi.getText());
        matrixC.setElement(user_input_C[no_of_entry], no_of_entry, 0);
    }

    public void set_eq_entry_panel_fields(){
        if(no_of_unknown >=1 ){
        coe_1.setText(user_input_A[no_of_entry][0].toString());
        }
        if(no_of_unknown >=2 ){
        coe_2.setText(user_input_A[no_of_entry][1].toString());
        }
        if(no_of_unknown >=3 ){
        coe_3.setText(user_input_A[no_of_entry][2].toString());
        }
        if(no_of_unknown >=4 ){
        coe_4.setText(user_input_A[no_of_entry][3].toString());
        }
        if(no_of_unknown >=5 ){
        coe_5.setText(user_input_A[no_of_entry][4].toString());
        }
        if(no_of_unknown >=6 ){
        coe_6.setText(user_input_A[no_of_entry][5].toString());
        }
        if(no_of_unknown >=7 ){
        coe_7.setText(user_input_A[no_of_entry][6].toString());
        }
        if(no_of_unknown >=8 ){
        coe_8.setText(user_input_A[no_of_entry][7].toString());
        }
        if(no_of_unknown >=9 ){
        coe_9.setText(user_input_A[no_of_entry][8].toString());
        }
        if(no_of_unknown >=10 ){
        coe_10.setText(user_input_A[no_of_entry][9].toString());
        }

        coe_multi.setText(user_input_C[no_of_entry].toString());
    }
    public void getSolution(){
        matrixB = matrixA.getInverse().multiply(matrixC);

        output_label.setText(matrixB.toString());
    }
    private void set_eq_entry_panel(){
        if(no_of_unknown < 1){
            coe_1.setVisible(false);
        }
        if(no_of_unknown < 2){
            coe_2.setVisible(false);
        }
        if(no_of_unknown < 3){
            coe_3.setVisible(false);
        }
        if(no_of_unknown < 4){
            coe_4.setVisible(false);
        }
        if(no_of_unknown < 5){
            coe_5.setVisible(false);
        }
        if(no_of_unknown < 6){
            coe_6.setVisible(false);
        }
        if(no_of_unknown < 7){
            coe_7.setVisible(false);
        }
        if(no_of_unknown < 8){
            coe_8.setVisible(false);
        }
        if(no_of_unknown < 9){
            coe_9.setVisible(false);
        }
        if(no_of_unknown < 10){
            coe_10.setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField coe_1;
    private javax.swing.JFormattedTextField coe_10;
    private javax.swing.JFormattedTextField coe_2;
    private javax.swing.JFormattedTextField coe_3;
    private javax.swing.JFormattedTextField coe_4;
    private javax.swing.JFormattedTextField coe_5;
    private javax.swing.JFormattedTextField coe_6;
    private javax.swing.JFormattedTextField coe_7;
    private javax.swing.JFormattedTextField coe_8;
    private javax.swing.JFormattedTextField coe_9;
    private javax.swing.JFormattedTextField coe_multi;
    private javax.swing.JButton eq_entry_cancel;
    private javax.swing.JButton eq_entry_next;
    private javax.swing.JPanel eq_entry_panel;
    private javax.swing.JButton eq_entry_previous;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton no_of_unknown_ok;
    private javax.swing.JPanel no_of_unknown_panel;
    private javax.swing.JComboBox no_of_unknown_value;
    private javax.swing.JButton output_done;
    private javax.swing.JLabel output_label;
    private javax.swing.JPanel output_panel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
